sdm_questionnaire/config/routes.rb
Rails.application.routes.draw do
  root 'submissions#index'
  get 'sessions/new', to: "sessions#new", as: :login
  post 'sessions/new', to: "sessions#create"
  delete 'logout' => 'sessions#destroy'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :answers
  resources :questions
  resources :submissions
  resources :questionnaires
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

sdm_questionnaire/app/models/questionnaire.rb
class Questionnaire < ApplicationRecord
	has_many :questions
	has_many :submissions
	validates  :name, presence: true
	accepts_nested_attributes_for :questions, allow_destroy: true, reject_if: :all_blank
end

sdm_questionnaire/app/controllers/questionnaires_controller.rb
class QuestionnairesController < ApplicationController
  before_action :go_login
  before_action :set_questionnaire, only: %i[ show edit update destroy ]
  
  # GET /questionnaires or /questionnaires.json
  def index
    @questionnaires = Questionnaire.all
  end

  # GET /questionnaires/1 or /questionnaires/1.json
  def show
  end

  # GET /questionnaires/new
  def new
    @questionnaire = Questionnaire.new
    @question_count = 0
  end

  # GET /questionnaires/1/edit
  def edit
  end

  # POST /questionnaires or /questionnaires.json
  def create
    @questionnaire = Questionnaire.new(questionnaire_params)
    respond_to do |format|
      if @questionnaire.save
        format.html { redirect_to @questionnaire, notice: "Questionnaire was successfully created." }
        format.json { render :show, status: :created, location: @questionnaire }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @questionnaire.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questionnaires/1 or /questionnaires/1.json
  def update
    respond_to do |format|
      if @questionnaire.update(questionnaire_params)
        format.html { redirect_to @questionnaire, notice: "Questionnaire was successfully updated." }
        format.json { render :show, status: :ok, location: @questionnaire }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @questionnaire.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questionnaires/1 or /questionnaires/1.json
  def destroy
    @questionnaire.destroy
    respond_to do |format|
      format.html { redirect_to questionnaires_url, notice: "Questionnaire was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_questionnaire
      @questionnaire = Questionnaire.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def questionnaire_params
      params.require(:questionnaire).permit(:name, questions_attributes: [:id, :text, :question_type, :possible_solutions, :_destroy])
    end
end

sdm_questionnaire/app/helpers/questionnaires_helper.rb
module QuestionnairesHelper
end

sdm_questionnaire/app/views/questionnaires/_form.html.erb
<%= nested_form_for @questionnaire do |f| %>
  <% if questionnaire.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(questionnaire.errors.count, "error") %> prohibited this questionnaire from being saved:</h2>

      <ul>
        <% questionnaire.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, required: true %>
  </div>
  <%= f.fields_for :questions do |question| %>
    <div class="question_fields">
      <%= question.label "Question" %>
      <%= question.text_field :text %>
      <%= question.hidden_field :possible_solutions %>
      <%= question.label :question_type %>
      <%= question.select :question_type, ['Open Answer', 'Multiple Choice', 'Single Choice', 'Number'], {}, {onChange: "change_question_type()", class: 'question_type_select'}%>
      <div class="possibleSolutions">
        <div><%= question.label "Possible Answers" %></div>
        <input class="possibleSolution"/><span onClick="addPossibleSolution()">Add Possible Answer</span>
      </div>
      <p onClick="confirmSolutions()">Done With Solutions</p>
      <%= question.link_to_remove "Remove this task" %>
    </div>
  <% end %>
  <p><%= f.link_to_add "Add a Question", :questions %></p>
  

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

sdm_questionnaire/app/views/questionnaires/edit.html.erb
<h1>Editing Questionnaire</h1>

<%= render 'form', questionnaire: @questionnaire %>

<%= link_to 'Show', @questionnaire %> |
<%= link_to 'Back', questionnaires_path %>

sdm_questionnaire/app/views/questionnaires/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Questionnaires</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questionnaires.each do |questionnaire| %>
      <tr>
        <td><%= questionnaire.name %></td>
        <td><%= link_to 'Show', questionnaire %></td>
        <td><%= link_to 'Edit', edit_questionnaire_path(questionnaire) %></td>
        <td><%= link_to 'Destroy', questionnaire, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Questionnaire', new_questionnaire_path %>

sdm_questionnaire/app/views/questionnaires/new.html.erb
<h1>New Questionnaire</h1>

<%= render 'form', questionnaire: @questionnaire %>

<%= link_to 'Back', questionnaires_path %>

sdm_questionnaire/app/views/questionnaires/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @questionnaire.name %>
</p>

<%= link_to 'Edit', edit_questionnaire_path(@questionnaire) %> |
<%= link_to 'Back', questionnaires_path %>


<ol>
<% @questionnaire.submissions.each do |s| %>
  <li><%= link_to s.email, s %></li>
<% end %>