sdm_questionnaire/config/routes.rb
Rails.application.routes.draw do
  root 'submissions#index'
  get 'sessions/new', to: "sessions#new", as: :login
  post 'sessions/new', to: "sessions#create"
  delete 'logout' => 'sessions#destroy'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :answers
  resources :questions
  resources :submissions
  resources :questionnaires
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

sdm_questionnaire/app/models/submission.rb
class Submission < ApplicationRecord
  belongs_to :questionnaire
  has_many :answers

  validates  :email, presence: true
  accepts_nested_attributes_for :answers, reject_if: :all_blank
end

sdm_questionnaire/app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  before_action :set_submission, only: %i[ show edit update destroy ]

  # GET /submissions or /submissions.json
  def index
    @questionnaires = Questionnaire.all
  end

  # GET /submissions/1 or /submissions/1.json
  def show
  end

  # GET /submissions/new
  def new
    @questionnaire = Questionnaire.find(params[:questionnaire_id].to_i)
    @submission = Submission.new(questionnaire: @questionnaire)
    @questions = @questionnaire.questions
    @questions.each do |q|
      @submission.answers.build(question_id: q.id)
    end
    @count = 1
  end

  # GET /submissions/1/edit
  def edit
  end

  # POST /submissions or /submissions.json
  def create
    @submission = Submission.new(submission_params)
    respond_to do |format|
      if @submission.save
        format.html { redirect_to submissions_path, notice: "Submission was successfully updated." }
        format.json { render :show, status: :ok, location: @submission }
      else
        puts @submission.errors.full_messages
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /submissions/1 or /submissions/1.json
  def update
    respond_to do |format|
      if @submission.update(submission_params)
        format.html { redirect_to @submission, notice: "Submission was successfully updated." }
        format.json { render :show, status: :ok, location: @submission }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /submissions/1 or /submissions/1.json
  def destroy
    @submission.destroy
    respond_to do |format|
      format.html { redirect_to submissions_url, notice: "Submission was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_submission
      @submission = Submission.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def submission_params
      params.require(:submission).permit(:questionnaire_id, :email, answers_attributes: [:id, :value, :value_array, :question_id, :submission_id])
    end
end

sdm_questionnaire/app/helpers/submissions_helper.rb
module SubmissionsHelper
end

sdm_questionnaire/app/views/submissions/_form.html.erb
<%= form_with(model: submission) do |form| %>
  <% if submission.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(submission.errors.count, "error") %> prohibited this submission from being saved:</h2>

      <ul>
        <% submission.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>



    <%=  form.fields_for :answers do |answer| %>
      <div class="field">
        <p>Question <%= @count %> - <%= @questions.find_by(id: answer.object.question_id).text %></p>

        <% if @questions.find_by(id: answer.object.question_id).possible_solutions_array %>

          <% if @questions.find_by(id: answer.object.question_id).question_type == "Multiple Choice" %>
            <%= answer.hidden_field :value %>  
            <% answer.object.question.possible_solutions_array.each do |ps| %>
              <input type="checkbox" name="possibleSolution" onChange="change_selected_answer('<%=ps%>')">
              <label for="possibleSolution"><%=ps%></label>
            <% end %>
          <% else %>
            <%= answer.select :value, @questions.find_by(id: answer.object.question_id).possible_solutions_array %>  
          <% end %>
        <% elsif @questions.find_by(id: answer.object.question_id).question_type == "Number" %>
          <%= answer.number_field :value, :required => true %>
        <% else %>    
          <%= answer.text_field :value, :required => true %>
        <% end %>

        <%= answer.hidden_field :question_id, value: answer.object.question_id %> 
        <%= answer.hidden_field :submission_id, value: @submission %> 
        <% @count += 1 %>
      </div>
    <% end %>

  <div class="field">
    <p><%= form.label :email %></p>
    <%= form.text_field :email, :required => true %>
  </div>

  <%= form.hidden_field :questionnaire_id, value: @submission.questionnaire_id %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

sdm_questionnaire/app/views/submissions/edit.html.erb
<h1>Editing Submission</h1>

<%= render 'form', submission: @submission %>

<%= link_to 'Show', @submission %> |
<%= link_to 'Back', submissions_path %>

sdm_questionnaire/app/views/submissions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Click on a Questionnaire to fill</h1>
<div class="cardView">
  <% @questionnaires.each do |questionnaire| %>
    <div>
      <h3><%= questionnaire.name %></h3>
      <%= link_to "", new_submission_path(:questionnaire_id => questionnaire.id), class: "hiddenLink" %>
    </div>
  <% end %>
</div>

sdm_questionnaire/app/views/submissions/new.html.erb
<%= link_to "Back", submissions_path %>
<h1>New Submission for <%= @submission.questionnaire.name %></h1>

<%= render 'form', submission: @submission %>

<%= link_to 'Back', submissions_path %>

sdm_questionnaire/app/views/submissions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Questionnaire:</strong>
  <%= @submission.questionnaire_id %>
</p>

<p>
  <strong>Email:</strong>
  <%= @submission.email %>
</p>

<%= link_to 'Edit', edit_submission_path(@submission) %> |
<%= link_to 'Back', submissions_path %>

<% @submission.answers.each do |q| %>
  <div class="field">
    <p>Question: <%= q.question.text %></p>
    <p>Answer: <%= q.value %>
  </div>
<% end %>